// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModelsProject.DataBase;

namespace ModelsProject.Migrations
{
    [DbContext(typeof(Arquivo))]
    [Migration("20190917142117_PrimeiraMigration")]
    partial class PrimeiraMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Publicacao", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AutorID");

                    b.Property<DateTime>("Data");

                    b.Property<double?>("MediaDeVotos");

                    b.Property<string>("Status");

                    b.Property<string>("Texto");

                    b.Property<string>("Tipo");

                    b.Property<string>("Titulo");

                    b.HasKey("ID");

                    b.HasIndex("AutorID");

                    b.ToTable("Publicacoes");
                });

            modelBuilder.Entity("ModelsProject.Comentario", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AutorComentarioId");

                    b.Property<string>("CitacaoId")
                        .IsRequired();

                    b.Property<string>("ComentarioId")
                        .IsRequired();

                    b.Property<DateTime>("Data");

                    b.Property<float?>("MediaDeVotos");

                    b.Property<string>("Message")
                        .IsRequired();

                    b.Property<float?>("Nota");

                    b.Property<string>("PublicacaoId")
                        .IsRequired();

                    b.Property<string>("mensagem");

                    b.HasKey("ID");

                    b.HasAlternateKey("AutorComentarioId");

                    b.HasAlternateKey("CitacaoId");

                    b.HasAlternateKey("ComentarioId");

                    b.HasAlternateKey("PublicacaoId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("ModelsProject.Usuario", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConfirmacaoDaSenha")
                        .IsRequired()
                        .HasMaxLength(12);

                    b.Property<DateTime>("Data");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(12);

                    b.HasKey("ID");

                    b.HasAlternateKey("Email");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Models.Publicacao", b =>
                {
                    b.HasOne("ModelsProject.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorID");
                });
#pragma warning restore 612, 618
        }
    }
}
